apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webpvc1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: httpdimg
        image: hitabrata/httpdimgage1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webmount
          mountPath: /var/www/html
      volumes:
      - name: webmount
        persistentVolumeClaim:
          claimName: webpvc1
---
kind: Service
apiVersion: v1
metadata:
  name: hostname-service
spec:
  type: NodePort
  selector:
    app: webserver
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 80
